export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const LOAD_FEATURED = 'LOAD_FEATURED'
export const FEATURED_LOADING = 'FEATURED_LOADING'
